# Generated by Django 2.2.6 on 2019-11-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('user_id', models.IntegerField(default=0, verbose_name='user_id')),
                ('xlocation', models.FloatField(verbose_name='xlocation')),
                ('ylocation', models.FloatField(verbose_name='ylocation')),
                ('param_1', models.BooleanField(default=False, verbose_name='param_1')),
                ('param_2', models.BooleanField(default=False, verbose_name='param_2')),
                ('param_3', models.BooleanField(default=False, verbose_name='param_3')),
                ('param_4', models.BooleanField(default=False, verbose_name='param_4')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_1', models.BooleanField(default=False, verbose_name='param_1')),
                ('param_2', models.BooleanField(default=False, verbose_name='param_2')),
                ('param_3', models.BooleanField(default=False, verbose_name='param_3')),
                ('param_4', models.BooleanField(default=False, verbose_name='param_4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
